### PR TITLE
Updates for my V20

### PR DESCRIPTION
**Pull request by swaneyjr**
I made a few adjustments to build this on my V20 with my updated version of Android Studio:
1) I updated the Gradle files (check to make sure you can still compile this!)
2) I edited Config, AndroidManifest.xml, and some other resources to allow for file editing on Android 7.0
3) I simplified some of the Camera2 logic with a repeating request, which should be more efficient and also cut down on the dead time between frames.

### CODE REVIEW

**Comment by mulhearn** [comment]
Thanks for this.  It looks good as far as I can tell.  I like the state machine in the App instance and the cleanup of the Camera init, the new handler, etc.  I have some questions:
 - What will be the effect of TEMPLATE_MANUAL replaced by TEMPLATE_PREVIEW?
 - I'll need to check I can still compile this with all the gradle changes and make changes as needed (I guess mostly likely just updating Android Studio).  What are the consequence of changing the target SDK version?  I think (phones in lab) I chose this to match my phone.  Does this matter much?

**Comment by mulhearn** [comment]
Use of AtomicInteger looks much cleaner too.

**Comment by swaneyjr** [comment]
1) I used TEMPLATE_PREVIEW because, for some reason, my phone doesn't know what to with TEMPLATE_MANUAL.  As I understand it, though, the difference is the default settings for creating the CameraCaptureSession.  In other words, if you manually set all of the values, it shouldn't matter which template you started with.

2) I don't think the target SDK version should make a huge difference for us.  The main reason I changed it is because Gradle was complaining that it didn't match the buildTools, or something like that.  In practice, I think it only should make a difference if your phone is up to that SDK version.  So for instance, back when the CRAYFIS app was targeting 21 and I bumped it to 24, I had to fix some of the app permissions that were changed in 23, since my phone is at 24.

**Comment by swaneyjr** [comment]
After playing with it though, I've found that it sometimes has trouble stopping and then restarting.  The reason I wanted to shift the state to the Application (rather than having it be static) is that when you stop and restart, you might spin up multiple instances of DaqService, both of which could be playing around with the static _state_ variable at the same time.  I'm going to try a quick fix, but I think it might benefit from a refactoring as an IntentService.  Whereas a plain Service is meant for indefinite background running, an IntentService is structured more for handling a queue of tasks.  So you could do something like post an Intent with the desired Config, the IntentService would do its thing, and once it's done, it would automatically get killed.

**Comment by mulhearn** [comment]
I think the plain Service is actually more what I have in mind.   In fact, I was even thinking of getting rid of the start/stop DAQ buttons, and just have the Application check if the service is running, and fire it up if not.  The service would simply twiddle it's thumbs unless there is an "enable" file present in the external storage area.  The point is so that you can start and stop data taking remotely with e.g. "touch ENABLE" and "rm ENABLE".

**Comment by mulhearn** [comment]
General point is that now that we have SSHelper, I want the App as dumb as possible.  Really just enough to let you take a run on an Airplane without having to bring a wifi router along, but otherwise, do everything via "ssh".

**Pull request closed without merging**
